In [ ]:
from google.colab import files
from google.colab import drive
drive.mount('/gdrive/')

Mounted at /gdrive/

In [ ]:
import warnings
warnings.filterwarnings("ignore")
import pandas as pd
import math
import statistics as stat
import numpy as np
import scipy.stats
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.gridspec as gridspec

In [ ]:
data= pd.read_csv('/gdrive/My Drive/KEEL_DATA_IR_1_to_9/glass-0-1-2-3_vs_4-5-6/glass-0-1-2-3_vs_4-5-6.csv', header=None)

In [ ]:
data

,0,1,2,3,4,5,6,7,8,9
0,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Class
1,1.51588824,12.87795,3.43036,1.40066,73.282,0.68931,8.04468,0,0.1224,negative
2,1.5176423,12.9777,3.53812,1.21127,73.002,0.65205,8.52888,0,0,negative
3,1.52212996,14.20795,3.82099,0.46976,71.77,0.11178,9.5726,0,0,negative
4,1.52222108,13.21045,3.7716,0.79076,71.9884,0.13041,10.2452,0,0,negative
...,...,...,...,...,...,...,...,...,...,...
210,1.51727782,14.70005,0,2.34119,73.282,0,8.94852,0.6615,0,positive
211,1.51622994,14.14145,0,2.88047,72.61,0.08073,9.18524,1.06155,0,positive
212,1.51837126,14.321,3.25974,2.21921,71.2492,1.45935,5.78508,1.62855,0,positive
213,1.51657164,14.7998,0,1.9913,73.1084,0,8.2814,1.71045,0,positive
214,1.51732338,14.95275,0,1.7987,72.9908,0,8.61496,1.5498,0,positive

In [ ]:
dict= {0:'RI',1:'Na',2:'Mg',3:'Al',4:'Si',5:'K',6:'Ca',7:'Ba',8:'Fe',9:'Class'}
data.rename(columns=dict,inplace=True)

In [ ]:
data.drop(data.index[:1], inplace=True)

In [ ]:
data.value_counts(data['Class'])

Class
 negative    163
 positive     51
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
# Encoding the Class Column:

labelencoder = LabelEncoder()

#Assigning numerical values and stroing it another column called Class_Numerical

data["Class_Numerical"]= labelencoder.fit_transform(data["Class"])

# Display new DataFrame:

data

,RI,Na,Mg,Al,Si,K,Ca,Ba,Fe,Class,Class_Numerical
1,1.51588824,12.87795,3.43036,1.40066,73.282,0.68931,8.04468,0,0.1224,negative,0
2,1.5176423,12.9777,3.53812,1.21127,73.002,0.65205,8.52888,0,0,negative,0
3,1.52212996,14.20795,3.82099,0.46976,71.77,0.11178,9.5726,0,0,negative,0
4,1.52222108,13.21045,3.7716,0.79076,71.9884,0.13041,10.2452,0,0,negative,0
5,1.51755118,13.39,3.65935,1.1888,72.7892,0.57132,8.27064,0,0.0561,negative,0
...,...,...,...,...,...,...,...,...,...,...,...
210,1.51727782,14.70005,0,2.34119,73.282,0,8.94852,0.6615,0,positive,1
211,1.51622994,14.14145,0,2.88047,72.61,0.08073,9.18524,1.06155,0,positive,1
212,1.51837126,14.321,3.25974,2.21921,71.2492,1.45935,5.78508,1.62855,0,positive,1
213,1.51657164,14.7998,0,1.9913,73.1084,0,8.2814,1.71045,0,positive,1
214,1.51732338,14.95275,0,1.7987,72.9908,0,8.61496,1.5498,0,positive,1

In [ ]:
data.drop(columns='Class',axis=1,inplace=True)

In [ ]:
# Converted the columns from Object to int/float

data["RI"] = data['RI'].astype('float')
data["Na"] = data['Na'].astype('float')
data["Mg"] = data['Mg'].astype('float')
data["Al"] = data['Al'].astype('float')
data["Si"] = data['Si'].astype('float')
data["K"] = data['K'].astype('float')
data["Ca"] = data['Ca'].astype('float')
data["Ba"] = data['Ba'].astype('float')
data["Fe"] = data['Fe'].astype('float')

In [ ]:
pip install modAL

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting modAL
  Downloading modAL-0.4.1-py3-none-any.whl (27 kB)
Requirement already satisfied: scipy>=0.18 in /usr/local/lib/python3.7/dist-packages (from modAL) (1.7.3)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.7/dist-packages (from modAL) (1.0.2)
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.7/dist-packages (from modAL) (1.21.6)
Requirement already satisfied: pandas>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from modAL) (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.1.0->modAL) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.1.0->modAL) (2022.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.1.0->modAL) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18->modAL) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.18->modAL) (3.1.0)
Installing collected packages: modAL
Successfully installed modAL-0.4.1

In [ ]:
pip install -U geometric-smote

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting geometric-smote
  Downloading geometric_smote-0.2.0-py3-none-any.whl (14 kB)
Requirement already satisfied: numpy>=1.1 in /usr/local/lib/python3.7/dist-packages (from geometric-smote) (1.21.6)
Requirement already satisfied: imbalanced-learn>=0.4.3 in /usr/local/lib/python3.7/dist-packages (from geometric-smote) (0.8.1)
Requirement already satisfied: scikit-learn>=0.21 in /usr/local/lib/python3.7/dist-packages (from geometric-smote) (1.0.2)
Requirement already satisfied: scipy>=0.17 in /usr/local/lib/python3.7/dist-packages (from geometric-smote) (1.7.3)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from imbalanced-learn>=0.4.3->geometric-smote) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.21->geometric-smote) (3.1.0)
Installing collected packages: geometric-smote
Successfully installed geometric-smote-0.2.0

In [ ]:
# Importing all Required modules
import warnings
warnings.filterwarnings("ignore")
from sklearn.decomposition import PCA
import matplotlib as mpl
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from functools import partial
#from modAL.batch import uncertainty_batch_sampling
from modAL.batch import uncertainty_batch_sampling, ranked_batch
from modAL.models import ActiveLearner,Committee
from sklearn.metrics import classification_report
import numpy as np
import pandas as pd
from sklearn.neighbors import LocalOutlierFactor
from numpy import quantile, where, random
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import OneClassSVM
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.feature_selection import RFE
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
import math
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import ADASYN
from imblearn.over_sampling import RandomOverSampler
from sklearn.ensemble import IsolationForest
from imblearn.over_sampling import BorderlineSMOTE
from gsmote import GeometricSMOTE

In [ ]:
def feature_selection(dataset,targets):
  """
  :param dataset: dataframe object containing all records of features
  :param targets: dataframe object of target values corresponding to dataset
  :return: returns new dataset with mentioned number of features
  """
  number_of_features = int(input("Total Number of features "+str(dataset.shape[1])+" , Enter number of best features needed:- "))
  selector = RFE(estimator=DecisionTreeClassifier(), n_features_to_select=number_of_features, step=1)
  selector.fit(dataset, targets)
  new_dataset = selector.transform(dataset)
  
  return pd.DataFrame(new_dataset)

In [ ]:
def Lof(data,number_of_top_outliers):
  """
  :param data: features values
  :param number_of_top_outliers: number of top ranked outliers
  :return: all top n outliers indices of data.
  """
  clf = LocalOutlierFactor(n_neighbors=2, algorithm='auto')
  y_pred = clf.fit_predict(data)
  score = clf.negative_outlier_factor_
  # very small number --> more the outlier
  # eg: -40000 --> outlier
  # -1.2  --> Not Outlier
  top_outlier_indices = score.argsort()[:number_of_top_outliers]
  return top_outlier_indices

In [ ]:
def OneClassSVMOutlier(data,number_of_top_outliers):
  """
  :param data: features values
  :param number_of_top_outliers: number of top ranked outliers
  :return: all top n outliers indices of data.
  """
  clf = OneClassSVM(kernel='linear',gamma='auto')
  y_pred = clf.fit_predict(data)
  score = clf.score_samples(data)
  # very small number --> more the outlier
  # eg: -40000 --> outlier
  # -1.2  --> Not Outlier
  top_outlier_indices = score.argsort()[:number_of_top_outliers]
  return top_outlier_indices

In [ ]:
def IForest(data,number_of_top_outliers):
  """
  :param data: features values
  :param number_of_top_outliers: number of top ranked outliers
  :return: all top n outliers indices of data.
  """
  clf = IsolationForest(random_state=0, max_samples='auto', n_estimators=100, max_features=1)
  y_pred = clf.fit_predict(data)
  score = clf.score_samples(data)
  
  top_outlier_indices = score.argsort()[:number_of_top_outliers]
  return top_outlier_indices

In [ ]:
from collections import Counter
n_maj = None
n_min = None

In [ ]:
# Actice Learning Main Module.
import time


if __name__ == '__main__':
  st1 = time.time()

    
  BATCH_SIZE=10
  N_RAW_SAMPLES= 100

  y_raw= data['Class_Numerical']
  X_raw= data.drop('Class_Numerical', axis=1)

  # Prompting User to select a feature selection option.
  # Upon selecting a valid option, Best features are selected.

  print("---------------------------------------")
  print("Select Feature Selection option\n1: Recursive Feature Selection\n2: No Feature Selection")
  fs_option = int(input())
  print("---------------------------------------")
  if(fs_option == 1):
    print("Starting Feature Selection using Random Forest")
    X_raw = feature_selection(X_raw, y_raw)

  print("Shape of data set :" + str(X_raw.shape))
  # converting data from dataframe to ndarray
  y_raw = y_raw.values
  X_raw = X_raw.values

  # batch_data_continous_X,y stores data and adds to it after every iteration of batch
  batch_data_continous_X = np.array([]).reshape(0,X_raw.shape[1])
  batch_data_continous_y = np.array([]).reshape(0,1)

  # Spliting dataset into Train, Pool(for batch) and Test.
  print("Preparing Initial Training, Pool and Test sets for initial AL")
  X_train, X_test, y_train, y_test = train_test_split(X_raw, y_raw, test_size=0.3, stratify=y_raw)
  X_train, X_pool, y_train, y_pool = train_test_split(X_train, y_train, test_size=0.3, stratify=y_train)

  print("training set size: "+str(len(X_train)))
  print("pool set size: " + str(len(X_pool)))
  print("test set size: " + str(len(X_test)))

  # lists to store all metric values after each iteration
  accuracy_history = []
  auc_history = []
  f1_minority_history = []
  GM_history = []
  dt = DecisionTreeClassifier()

  # Prompting User to Active Learning Strategy from the list of available options.
  # Upon selecting a valid option, it creates batches using Active Learning Strategy provided.
  print("---------------------------------------")
  print("Select Strategy\n1: Ranked Batch using Uncertainity\n2: Query By Committee Batch")
  strategy_option = int(input())
  print("---------------------------------------")

  # Prompting User to provide batch size eg: 10.
  print("---------------------------------------")
  print("Enter Batch Size :(Default is 10)\n")
  BATCH_SIZE = int(input())
  N_RAW_SAMPLES = 10 * BATCH_SIZE
  print("---------------------------------------")

  # Prompting User to select an outlier detection method from the list of available options.
  # Upon selecting a valid option, it gets best outliers for every batch.
  print("---------------------------------------")
  print("Enter Outlier Detection Method")
  outlier_option = int(input(("1: LOF\n2: One Class SVM\n3: IForest\n4: No Outlier")))
  print("---------------------------------------")

  # Prompting User to select Data Sampling method from the list of available options.
  # Upon selecting a valid option, it samples batch_data_continous_X,y data for every batch.
  print("---------------------------------------")
  print("Enter Data sampling Technique for Imbalanced Data")
  sampling_option = int(input(("1: SMOTE\n2: ADASYN\n3: Random Oversampling\n4: No Sampling\n5: BorderlineSMOTE\n6: Geometric-SMOTE")))
  print("---------------------------------------")

  if(strategy_option == 1): # if option is Uncertainty Sampling
    if(outlier_option == 4): # No outlier detection
      preset_batch = partial(uncertainty_batch_sampling, n_instances=int(BATCH_SIZE))
    else:
      preset_batch = partial(uncertainty_batch_sampling, n_instances=int(BATCH_SIZE*0.7))
    # Specify our active learning model.
    learner = ActiveLearner(estimator=dt, X_training=X_train, y_training=y_train, query_strategy=preset_batch)

  elif(strategy_option == 2): # If option chosen is Query By Committee
    n_members = 2
    n_initial = len(X_train)
    learner_list = list()
    for member_idx in range(n_members): #Random index

      train_idx = np.random.choice(range(X_train.shape[0]), size=int(n_initial/n_members), replace=False)
      X_train_temp = X_train[train_idx]
      y_train_temp = y_train[train_idx]

      # creating a reduced copy of the data with the known instances removed
      X_train = np.delete(X_train, train_idx, axis=0)
      y_train = np.delete(y_train, train_idx)

      # initializing learner
      learnerAL = ActiveLearner(estimator=RandomForestClassifier(), X_training=X_train_temp, y_training=y_train_temp)
      learner_list.append(learnerAL)

    # assembling the committee
    learner = Committee(learner_list=learner_list)

  batch_data_continous_X = np.vstack([batch_data_continous_X, X_train])
  batch_data_continous_y = np.append(batch_data_continous_y, y_train)



  '''# Initial training with trainset
  print("========================")
  print("Initial Training Results")
  # Isolate the data we'll need for plotting.
  predictions = learner.predict(X_test)
  is_correct = (predictions == y_test)

  model_accuracy = learner.score(X_test, y_test)
  predictions = learner.predict(X_test)
  print("========================")
  print('Accuracy after query {n}: {acc:0.4f}'.format(n=0, acc=model_accuracy))
  #print("This is"+ " "+ str(x+1) +" " + "iteration.")
  print(confusion_matrix(y_test, predictions))
  print(classification_report(y_test, predictions))
  print("AUC: "+str(roc_auc_score(y_test, predictions)))
  accuracy_history.append(model_accuracy)
  auc_history.append(roc_auc_score(y_test, predictions))
  f1_minority_history.append(f1_score(y_test, predictions, average=None)[-1])
  recal_values = recall_score(y_test, predictions, average=None)
  GM_history.append(math.sqrt(recal_values[0]*recal_values[-1]))'''
  
  N_QUERIES = int(N_RAW_SAMPLES // BATCH_SIZE)
  print("========================")
  print("Learning phase with "+ str(N_QUERIES)+" queries")
  print("Total number of records per batch "+ str(BATCH_SIZE)+"  divided into")
  if(outlier_option == 4):
    print("Uncertain samples: " + str(int(BATCH_SIZE)))
    print("outlier samples: 0")
  else:
    print("Uncertain samples: " + str(int(BATCH_SIZE * 0.7)))
    print("outlier samples: " + str(int(BATCH_SIZE * 0.3)))
    
  print("========================")
  for index in range(N_QUERIES):
    print("---------------------------------------")
    print("Learning phase Query: " + str(index + 1))

    print("Getting pool of data for learner using selected sampling method")
      
    if(strategy_option == 1):
      query_index, query_instance = learner.query(X_pool)
      # Teach our ActiveLearner model the record it has requested.
      X_batch, y_batch = X_pool[query_index], y_pool[query_index]
        
      # Remove the queried instance from the unlabeled pool.
      X_pool = np.delete(X_pool, query_index, axis=0)
      y_pool = np.delete(y_pool, query_index)
        
    elif (strategy_option == 2):

      if(outlier_option == 4):
        strategy_batch_size = int(BATCH_SIZE)
      else:
        strategy_batch_size = int(BATCH_SIZE*0.7)
        
      X_batch = np.array([]).reshape(0,X_pool.shape[1]) #reshaping an empty list
      y_batch = np.array([]).reshape(0,1)
      for strategy_batch_size_i in range(strategy_batch_size):
        
        query_index, query_instance = learner.query(X_pool)
        #Teach our ActiveLearner model the record it has requested.
        X_batch = np.vstack([X_batch, X_pool[query_index]])
        y_batch = np.append(y_batch, y_pool[query_index])

        # Remove the queried instance from the unlabeled pool.
        X_pool = np.delete(X_pool, query_index, axis=0)
        y_pool = np.delete(y_pool, query_index)


    print("getting Outliers from data pool")
    if(outlier_option == 1):
      outlier_index = Lof(X_pool, int(BATCH_SIZE*0.3))
    elif(outlier_option == 2):
      outlier_index = OneClassSVMOutlier(X_pool, int(BATCH_SIZE*0.3))
    elif(outlier_option == 3):
      outlier_index = IForest(X_pool, int(BATCH_SIZE * 0.3))
    else:
      outlier_index = []

    # Teach our ActiveLearner model the outlier record it has requested.
    X_outlier, y_outlier = X_pool[outlier_index], y_pool[outlier_index]

    # Remove the outlier instance from the unlabeled pool.
    X_pool = np.delete(X_pool, outlier_index, axis=0)
    y_pool = np.delete(y_pool, outlier_index)


    X_batch_l = X_batch.tolist()
    y_batch_l = y_batch.tolist()

    X_outlier_l =  X_outlier.tolist()
    y_outlier_l = y_outlier.tolist()

    X_batch_l.extend(X_outlier_l)
    y_batch_l.extend(y_outlier_l)

    X = np.array(X_batch_l)
    y = np.array(y_batch_l)

    batch_data_continous_X = np.vstack([batch_data_continous_X, X])
    batch_data_continous_y = np.append(batch_data_continous_y, y)
    n_maj = Counter(batch_data_continous_y)[0]
    n_min = Counter(batch_data_continous_y)[1]
    print("Imbalanced Ratio:",n_maj/n_min)
    
    # ============================================ The new portion needs to be added here =================================================
    
  #teach_X = []
  #teach_y = []
  print("Data Sampling with selected option")
  '''if(sampling_option == 1):
      oversample = SMOTE(k_neighbors=1)
      teach_X, teach_y = oversample.fit_resample(batch_data_continous_X, batch_data_continous_y)
    elif(sampling_option == 2):
      oversample = ADASYN()
      teach_X, teach_y = oversample.fit_resample(batch_data_continous_X, batch_data_continous_y)
    elif(sampling_option == 3):
      oversample = RandomOverSampler(sampling_strategy='minority')
      teach_X, teach_y = oversample.fit_resample(batch_data_continous_X, batch_data_continous_y)
    else:
      teach_X = batch_data_continous_X
      teach_y = batch_data_continous_y'''
  teach_X = batch_data_continous_X
  teach_y = batch_data_continous_y  
  print("teach with query using uncertainity and outlier data")
  learner.teach(X=teach_X, y=teach_y)

  # Calculate and report our model's accuracy.
  model_accuracy = learner.score(X_test, y_test)
  predictions = learner.predict(X_test)
  print("========================")
  print('Accuracy after query {n}: {acc:0.4f}'.format(n=index + 1, acc=model_accuracy))

  print(confusion_matrix(y_test, predictions))
  print(classification_report(y_test, predictions))
  print("AUC: " + str(roc_auc_score(y_test, predictions)))

  accuracy_history.append(model_accuracy)
  auc_history.append(roc_auc_score(y_test, predictions))
  f1_minority_history.append(f1_score(y_test, predictions, average=None)[-1])
  recal_values = recall_score(y_test, predictions, average=None)
  GM_history.append(math.sqrt(recal_values[0] * recal_values[-1]))

  ilO_auc, ilO_f1, ilO_gm = ([] for i in range(3))
  ilO_auc= auc_history.copy()
  ilO_f1 = f1_minority_history.copy()
  ilO_gm = GM_history.copy()

  et1 = time.time()
  elapsed_time1 = et1-st1
  print("Elapsed time:",elapsed_time1,"seconds")

---------------------------------------
Select Feature Selection option
1: Recursive Feature Selection
2: No Feature Selection
2
---------------------------------------
Shape of data set :(214, 9)
Preparing Initial Training, Pool and Test sets for initial AL
training set size: 104
pool set size: 45
test set size: 65
---------------------------------------
Select Strategy
1: Ranked Batch using Uncertainity
2: Query By Committee Batch
1
---------------------------------------
---------------------------------------
Enter Batch Size :(Default is 10)

2
---------------------------------------
---------------------------------------
Enter Outlier Detection Method
1: LOF
2: One Class SVM
3: IForest
4: No Outlier4
---------------------------------------
---------------------------------------
Enter Data sampling Technique for Imbalanced Data
1: SMOTE
2: ADASYN
3: Random Oversampling
4: No Sampling
5: BorderlineSMOTE
6: Geometric-SMOTE6
---------------------------------------
========================
Learning phase with 10 queries
Total number of records per batch 2  divided into
Uncertain samples: 2
outlier samples: 0
========================
---------------------------------------
Learning phase Query: 1
Getting pool of data for learner using selected sampling method
getting Outliers from data pool
Imbalanced Ratio: 2.925925925925926
---------------------------------------
Learning phase Query: 2
Getting pool of data for learner using selected sampling method
getting Outliers from data pool
Imbalanced Ratio: 2.857142857142857
---------------------------------------
Learning phase Query: 3
Getting pool of data for learner using selected sampling method
getting Outliers from data pool
Imbalanced Ratio: 2.793103448275862
---------------------------------------
Learning phase Query: 4
Getting pool of data for learner using selected sampling method
getting Outliers from data pool
Imbalanced Ratio: 2.7333333333333334
---------------------------------------
Learning phase Query: 5
Getting pool of data for learner using selected sampling method
getting Outliers from data pool
Imbalanced Ratio: 2.8
---------------------------------------
Learning phase Query: 6
Getting pool of data for learner using selected sampling method
getting Outliers from data pool
Imbalanced Ratio: 2.8666666666666667
---------------------------------------
Learning phase Query: 7
Getting pool of data for learner using selected sampling method
getting Outliers from data pool
Imbalanced Ratio: 2.806451612903226
---------------------------------------
Learning phase Query: 8
Getting pool of data for learner using selected sampling method
getting Outliers from data pool
Imbalanced Ratio: 2.870967741935484
---------------------------------------
Learning phase Query: 9
Getting pool of data for learner using selected sampling method
getting Outliers from data pool
Imbalanced Ratio: 2.8125
---------------------------------------
Learning phase Query: 10
Getting pool of data for learner using selected sampling method
getting Outliers from data pool
Imbalanced Ratio: 2.757575757575758
Data Sampling with selected option
teach with query using uncertainity and outlier data
========================
Accuracy after query 10: 0.9077
[[47  3]
 [ 3 12]]
              precision    recall  f1-score   support

           0       0.94      0.94      0.94        50
           1       0.80      0.80      0.80        15

    accuracy                           0.91        65
   macro avg       0.87      0.87      0.87        65
weighted avg       0.91      0.91      0.91        65

AUC: 0.87
Elapsed time: 9.689177989959717 seconds

In [ ]:
# =============================================== Calulating the Imbalance Ratio and the Oversampling ==============================================
st2= time.time()
print(sampling_option)
#print(batch_data_continous_X.shape)
print(pd.DataFrame(batch_data_continous_y).value_counts())
IR=1.5
if (n_maj/n_min>IR):
  print("Resampling is Required:")
  if(sampling_option == 1):
    oversample = SMOTE(k_neighbors=5, sampling_strategy='minority')
    teach_X, teach_y = oversample.fit_resample(batch_data_continous_X, batch_data_continous_y)
  elif(sampling_option == 2):
    oversample = ADASYN(k_neighbors=3, sampling_strategy='minority')
    teach_X, teach_y = oversample.fit_resample(batch_data_continous_X, batch_data_continous_y)
  elif(sampling_option == 3):
    oversample = RandomOverSampler(sampling_strategy='minority')
    teach_X, teach_y = oversample.fit_resample(batch_data_continous_X, batch_data_continous_y)
  elif(sampling_option == 5):
    oversample = BorderlineSMOTE(random_state=42, sampling_strategy='minority', k_neighbors=5)
    teach_X, teach_y = oversample.fit_resample(batch_data_continous_X, batch_data_continous_y)
  elif(sampling_option == 6):
    oversample = GeometricSMOTE(sampling_strategy='minority', k_neigbors=5)
    teach_X, teach_y = oversample.fit_resample(batch_data_continous_X, batch_data_continous_y)
  else:
    teach_X = batch_data_continous_X
    teach_y = batch_data_continous_y
  
  #teach_X = batch_data_continous_X
  #teach_y = batch_data_continous_y  

  #Shape of teach_x and y:
  #print(teach_X.shape)
  print(pd.DataFrame(teach_y).value_counts())

  print("teach with query using uncertainity and outlier data")
  learner.teach(X=teach_X, y=teach_y)

  # Calculate and report our model's accuracy.
  model_accuracy = learner.score(X_test, y_test)
  predictions = learner.predict(X_test)
  print("========================")
  print('Accuracy after query {n}: {acc:0.4f}'.format(n=index + 1, acc=model_accuracy))

  print(confusion_matrix(y_test, predictions))
  print(classification_report(y_test, predictions))
  print("AUC: " + str(roc_auc_score(y_test, predictions)))

  accuracy_history.append(model_accuracy)
  auc_history.append(roc_auc_score(y_test, predictions))
  f1_minority_history.append(f1_score(y_test, predictions, average=None)[-1])
  recal_values = recall_score(y_test, predictions, average=None)
  GM_history.append(math.sqrt(recal_values[0] * recal_values[-1]))

  ilN_auc, ilN_f1, ilN_gm = ([] for i in range(3))

  ilN_auc= auc_history.copy()
  ilN_f1 = f1_minority_history.copy()
  ilN_gm = GM_history.copy()
  et2 = time.time()
  elapsed_time2 = et2 - st2
  tot_time = elapsed_time1+elapsed_time2
  print("Total time:",tot_time,"seconds")

6
0.0    91
1.0    33
dtype: int64
Resampling is Required:
0.0    91
1.0    91
dtype: int64
teach with query using uncertainity and outlier data
========================
Accuracy after query 10: 0.9231
[[47  3]
 [ 2 13]]
              precision    recall  f1-score   support

           0       0.96      0.94      0.95        50
           1       0.81      0.87      0.84        15

    accuracy                           0.92        65
   macro avg       0.89      0.90      0.89        65
weighted avg       0.93      0.92      0.92        65

AUC: 0.9033333333333333
Total time: 9.724071502685547 seconds

In [ ]:
#print(accuracy_history)
print(auc_history)
print(f1_minority_history)
print(GM_history)

[0.88, 0.87]
[0.8275862068965518, 0.8000000000000002]
[0.8763560920082658, 0.867179335547152]

In [ ]:

#global_list = list()
#global_list.append([[il_auc],[il_f1],[il_gm]])
global_list.extend(ilN_auc+ilN_f1+ilN_gm)

In [ ]:
print(global_list)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.9333333333333333, 0.9333333333333333, 0.9285714285714286, 0.9285714285714286, 0.9309493362512627, 0.9309493362512627, 0.8966666666666667, 0.9166666666666666, 0.7777777777777778, 0.8235294117647058, 0.8959166627910582, 0.9165151389911681, 0.9333333333333333, 0.9333333333333333, 0.9285714285714286, 0.9285714285714286, 0.9309493362512627, 0.9309493362512627, 0.9466666666666667, 0.9466666666666667, 0.9032258064516129, 0.9032258064516129, 0.9465727652959386, 0.9465727652959386, 1.0, 0.99, 1.0, 0.967741935483871, 1.0, 0.9899494936611666, 0.8566666666666667, 0.8466666666666667, 0.8148148148148148, 0.7857142857142856, 0.8477420991472976, 0.8390470785361213, 0.8233333333333333, 0.89, 0.7692307692307692, 0.8571428571428571, 0.8082903768654761, 0.8854377448471462, 0.9333333333333333, 0.9, 0.9285714285714286, 0.888888888888889, 0.9309493362512627, 0.8944271909999159, 0.9233333333333333, 0.9233333333333333, 0.896551724137931, 0.896551724137931, 0.9215928240461366, 0.9215928240461366, 0.8600000000000001, 0.8600000000000001, 0.7741935483870969, 0.7741935483870969, 0.8579044235810888, 0.8579044235810888, 0.9133333333333333, 0.89, 0.8666666666666667, 0.8571428571428571, 0.9121403400793103, 0.8854377448471462, 0.89, 0.88, 0.8571428571428571, 0.8275862068965518, 0.8854377448471462, 0.8763560920082658, 0.9133333333333333, 0.9133333333333333, 0.8666666666666667, 0.8666666666666667, 0.9121403400793103, 0.9121403400793103, 0.9166666666666666, 0.9266666666666667, 0.8235294117647058, 0.8484848484848485, 0.9165151389911681, 0.9266426855410163, 0.8133333333333332, 0.78, 0.7407407407407408, 0.6923076923076923, 0.7999999999999999, 0.758946638440411, 0.9266666666666667, 0.9266666666666667, 0.8484848484848485, 0.8484848484848485, 0.9266426855410163, 0.9266426855410163, 0.8233333333333333, 0.8666666666666667, 0.7692307692307692, 0.846153846153846, 0.8082903768654761, 0.8563488385776752, 0.8733333333333334, 0.9366666666666666, 0.7647058823529413, 0.8749999999999999, 0.8733078876700168, 0.9366607354497857, 0.9366666666666666, 0.9366666666666666, 0.8749999999999999, 0.8749999999999999, 0.9366607354497857, 0.9366607354497857, 1.0, 0.9566666666666667, 1.0, 0.9333333333333333, 1.0, 0.9563820714895624, 0.99, 0.99, 0.967741935483871, 0.967741935483871, 0.9899494936611666, 0.9899494936611666, 0.9466666666666667, 0.97, 0.9032258064516129, 0.9090909090909091, 0.9465727652959386, 0.9695359714832658, 0.97, 0.98, 0.9090909090909091, 0.9375, 0.9695359714832658, 0.9797958971132712]

In [ ]:
len(global_list)

144

In [ ]:
chunk_size = 2
chunked_list = [global_list[i:i+chunk_size] for i in range(0, len(global_list), chunk_size)]
print(chunked_list)

[[1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [0.9333333333333333, 0.9333333333333333], [0.9285714285714286, 0.9285714285714286], [0.9309493362512627, 0.9309493362512627], [0.8966666666666667, 0.9166666666666666], [0.7777777777777778, 0.8235294117647058], [0.8959166627910582, 0.9165151389911681], [0.9333333333333333, 0.9333333333333333], [0.9285714285714286, 0.9285714285714286], [0.9309493362512627, 0.9309493362512627], [0.9466666666666667, 0.9466666666666667], [0.9032258064516129, 0.9032258064516129], [0.9465727652959386, 0.9465727652959386], [1.0, 0.99], [1.0, 0.967741935483871], [1.0, 0.9899494936611666], [0.8566666666666667, 0.8466666666666667], [0.8148148148148148, 0.7857142857142856], [0.8477420991472976, 0.8390470785361213], [0.8233333333333333, 0.89], [0.7692307692307692, 0.8571428571428571], [0.8082903768654761, 0.8854377448471462], [0.9333333333333333, 0.9], [0.9285714285714286, 0.888888888888889], [0.9309493362512627, 0.8944271909999159], [0.9233333333333333, 0.9233333333333333], [0.896551724137931, 0.896551724137931], [0.9215928240461366, 0.9215928240461366], [0.8600000000000001, 0.8600000000000001], [0.7741935483870969, 0.7741935483870969], [0.8579044235810888, 0.8579044235810888], [0.9133333333333333, 0.89], [0.8666666666666667, 0.8571428571428571], [0.9121403400793103, 0.8854377448471462], [0.89, 0.88], [0.8571428571428571, 0.8275862068965518], [0.8854377448471462, 0.8763560920082658], [0.9133333333333333, 0.9133333333333333], [0.8666666666666667, 0.8666666666666667], [0.9121403400793103, 0.9121403400793103], [0.9166666666666666, 0.9266666666666667], [0.8235294117647058, 0.8484848484848485], [0.9165151389911681, 0.9266426855410163], [0.8133333333333332, 0.78], [0.7407407407407408, 0.6923076923076923], [0.7999999999999999, 0.758946638440411], [0.9266666666666667, 0.9266666666666667], [0.8484848484848485, 0.8484848484848485], [0.9266426855410163, 0.9266426855410163], [0.8233333333333333, 0.8666666666666667], [0.7692307692307692, 0.846153846153846], [0.8082903768654761, 0.8563488385776752], [0.8733333333333334, 0.9366666666666666], [0.7647058823529413, 0.8749999999999999], [0.8733078876700168, 0.9366607354497857], [0.9366666666666666, 0.9366666666666666], [0.8749999999999999, 0.8749999999999999], [0.9366607354497857, 0.9366607354497857], [1.0, 0.9566666666666667], [1.0, 0.9333333333333333], [1.0, 0.9563820714895624], [0.99, 0.99], [0.967741935483871, 0.967741935483871], [0.9899494936611666, 0.9899494936611666], [0.9466666666666667, 0.97], [0.9032258064516129, 0.9090909090909091], [0.9465727652959386, 0.9695359714832658], [0.97, 0.98], [0.9090909090909091, 0.9375], [0.9695359714832658, 0.9797958971132712]]

In [ ]:
df_US = pd.DataFrame(chunked_list, columns = ['Previous_Method','New_Method'])

In [ ]:
df_US

    Previous_Method  New_Method
0          1.000000    1.000000
1          1.000000    1.000000
2          1.000000    1.000000
3          0.933333    0.933333
4          0.928571    0.928571
..              ...         ...
67         0.903226    0.909091
68         0.946573    0.969536
69         0.970000    0.980000
70         0.909091    0.937500
71         0.969536    0.979796

[72 rows x 2 columns]

In [ ]:
#Converting the dataframe into excel and saving the result
df_US.to_excel('/gdrive/My Drive/KEEL_DATA_IR_1_to_9/glass-0-1-2-3_vs_4-5-6/QBC_new.xlsx')